# Generated by Django 4.1.1 on 2022-10-05 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosen', '0002_dosen_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='no',
        ),
    ]
